### PR TITLE
make nsfw part of default cogs

### PR DESCRIPTION
**Pull request by XAOS1502**
:heart:

### CODE REVIEW

**Comment by fourjr** [comment]
shouldnt be a default cog? :thonk:

**Comment by fourjr** [comment]
ok then /shrug

**Comment by XAOS1502** [comment]
Wait, wasn't there a way to have some cogs disabled and load them via command?

**Comment by fourjr** [comment]
Pretty sure @verixx removed it

**Comment by XAOS1502** [comment]
I might be able to find that, somewhere in the history. Let me do it and pr once ready

**Comment by fourjr** [comment]
Look up bot.load_extension on rewrite docs iirc

**Comment by XAOS1502** [comment]
That wasn't so hard. Found it!

**Comment by fourjr** [comment]
PR it :)

**Pull request merged**
