### PR TITLE
Added mod.py (only one command so far tho)

### PR DESCRIPTION
**Pull request by isaacli430**

### CODE REVIEW

**Comment by isaacli430** [comment]
I also just changed emoji size so that it's a little more manageable, and I added aliases to it

**Comment by isaacli430** [comment]
ignore those last 4 commits, I was just updating my repo

**Comment by isaacli430** [comment]
Added ban

**Review by 0arm — CHANGES_REQUESTED** [review]
Im gonna have to close it, too much shit going on, making a seperate request to shrink the size is not efficient.

**Pull request closed without merging**
