### PR TITLE
Update mod.py

### PR DESCRIPTION
**Pull request by andrija535**
I added mute and unmute command. I am not sure if they work since I couldn't really test them.

### CODE REVIEW

**Review by fourjr — CHANGES_REQUESTED** [review]
Shouldn't be "Oh looks like I didn't specify a reason" for member==None :eyes:

For unmute, it should delete the channel override and not set it to True. Just so that you won't have a bunch of random overrides.

**Comment by fourjr** [comment]
You can test them if you add them to your own fork and try to mute someone from your own Self Bot :)

**Comment by andrija535** [comment]
I changed those, for deleting override, I did not do that, instead I made two overrides that are used instead of creating new ones

**Comment by 0arm** [comment]
This doesnt work. The indentation is even off

**Comment by andrija535** [comment]
I fixed my mistakes

**Comment by andrija535** [comment]
Hopefully it works now

**Review by fourjr — CHANGES_REQUESTED** [review]
Indentation error in the whole thing?
Line 40/41 to be pushed one space forward and.. 165 to 183 four spaces forward.

**Review by fourjr — APPROVED** [review]

**Comment by fourjr** [comment]
Will implement after modifying a bit in the next commit

**Comment by fourjr** [comment]
https://github.com/verixx/selfbot.py/commit/7436f4b4bd1186e2d863ebbdf51d11cee6fb330f

**Pull request closed without merging**
