### PR TITLE
Well, since you asked...

### PR DESCRIPTION
**Pull request by XAOS1502**
😍 bunbun ❤️

### CODE REVIEW

**Comment by XAOS1502** [comment]
@fourjr

**Comment by fourjr** [comment]
<3

**Comment by XAOS1502** [comment]
🤔

**Comment by XAOS1502** [comment]
Someone has to accept this community cog

**Comment by fourjr** [comment]
I'm editing it first so people dont get this version

**Review by fourjr — CHANGES_REQUESTED** [review]
Don't merge this, I'll merge it.

**Comment by XAOS1502** [comment]
😲

**Comment by fourjr** [comment]
Merged https://github.com/verixx/selfbot.py/commit/3f53fd431332f85faa7c019b08080b3e24c68a70
Did it that way as I didnt want ccs to affect anything, couldnt edit that with gitweb for some reason

**Pull request closed without merging**
